version: '3'

services:
  #NODE CONTAINER
  backend: 
    build: ./backend
    expose: 
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST} 
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./backend/server/:/app/cct-backend/server/
    command: npm run start-dev

  #REACT CONTAINER
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./frontend/src:/app/cct-frontend/src
      - ./frontend/public:/app/cct-frontend/public
    links:
      - backend
    command: npm run start